127.0.0.1 - - [11/Jul/2025 15:46:57] "HEAD / HTTP/1.1" 200 -
127.0.0.1 - - [11/Jul/2025 15:52:39] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [11/Jul/2025 15:52:40] "GET /app.js HTTP/1.1" 200 -
127.0.0.1 - - [11/Jul/2025 15:52:40] "GET /styles.css HTTP/1.1" 200 -
127.0.0.1 - - [11/Jul/2025 15:52:41] code 404, message File not found
127.0.0.1 - - [11/Jul/2025 15:52:41] "GET /favicon.ico HTTP/1.1" 404 -
----------------------------------------
Exception occurred during processing of request from ('127.0.0.1', 54474)
Traceback (most recent call last):
  File "/usr/lib/python3.13/http/server.py", line 731, in send_head
    f = open(path, 'rb')
FileNotFoundError: [Errno 2] No such file or directory: '/home/ultimatebrok/Downloads/ECharts-test-2/favicon.ico'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.13/socketserver.py", line 697, in process_request_thread
    self.finish_request(request, client_address)
    ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.13/http/server.py", line 1320, in finish_request
    self.RequestHandlerClass(request, client_address, self,
    ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                             directory=args.directory)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.13/http/server.py", line 672, in __init__
    super().__init__(*args, **kwargs)
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.13/socketserver.py", line 766, in __init__
    self.handle()
    ~~~~~~~~~~~^^
  File "/usr/lib/python3.13/http/server.py", line 436, in handle
    self.handle_one_request()
    ~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/lib/python3.13/http/server.py", line 424, in handle_one_request
    method()
    ~~~~~~^^
  File "/usr/lib/python3.13/http/server.py", line 676, in do_GET
    f = self.send_head()
  File "/usr/lib/python3.13/http/server.py", line 733, in send_head
    self.send_error(HTTPStatus.NOT_FOUND, "File not found")
    ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.13/http/server.py", line 491, in send_error
    self.wfile.write(body)
    ~~~~~~~~~~~~~~~~^^^^^^
  File "/usr/lib/python3.13/socketserver.py", line 845, in write
    self._sock.sendall(b)
    ~~~~~~~~~~~~~~~~~~^^^
BrokenPipeError: [Errno 32] Broken pipe
----------------------------------------
127.0.0.1 - - [11/Jul/2025 15:55:12] "GET / HTTP/1.1" 304 -
127.0.0.1 - - [11/Jul/2025 15:55:12] "GET /app.js HTTP/1.1" 200 -
127.0.0.1 - - [11/Jul/2025 15:58:30] "GET / HTTP/1.1" 304 -
127.0.0.1 - - [11/Jul/2025 15:58:30] "GET /styles.css HTTP/1.1" 304 -
127.0.0.1 - - [11/Jul/2025 15:58:30] "GET /app.js HTTP/1.1" 304 -
